"""empty message

Revision ID: 71107028d9b8
Revises: 
Create Date: 2024-01-25 16:36:07.732909

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '71107028d9b8'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=True),
    sa.Column('email', sa.String(), nullable=True),
    sa.Column('mobile', sa.String(), nullable=True),
    sa.Column('password', sa.String(), nullable=True),
    sa.Column('role', sa.Enum('user', 'admin', 'owner', name='roles'), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('user_id'),
    sa.UniqueConstraint('email')
    )
    op.create_index(op.f('ix_users_user_id'), 'users', ['user_id'], unique=False)
    op.create_table('room_details',
    sa.Column('room_id', sa.Integer(), nullable=False),
    sa.Column('locality', sa.String(), nullable=True),
    sa.Column('address', sa.String(), nullable=True),
    sa.Column('bhk', sa.Enum('rk', 'one_bhk', 'two_bhk', 'three_bhk', 'four_bhk', name='bhk'), nullable=True),
    sa.Column('beds', sa.String(), nullable=True),
    sa.Column('rent', sa.Integer(), nullable=True),
    sa.Column('carpet_area', sa.Float(), nullable=True),
    sa.Column('amenities', sa.Enum('full_furnished', 'semi_furnished', 'unfurnished', name='amenities'), nullable=True),
    sa.Column('services', sa.Enum('wifi', 'food', 'washing_machine', 'fridge', 'closet', 'parking', 'lift', name='services'), nullable=True),
    sa.Column('category', sa.Enum('flat', 'pg', 'hostel', name='category'), nullable=True),
    sa.Column('owner_name', sa.String(), nullable=True),
    sa.Column('owner_mobile', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.user_id'], ),
    sa.PrimaryKeyConstraint('room_id'),
    sa.UniqueConstraint('user_id')
    )
    op.create_table('history',
    sa.Column('history_id', sa.Integer(), nullable=False),
    sa.Column('history', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('room_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['room_id'], ['room_details.room_id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.user_id'], ),
    sa.PrimaryKeyConstraint('history_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('history')
    op.drop_table('room_details')
    op.drop_index(op.f('ix_users_user_id'), table_name='users')
    op.drop_table('users')
    # ### end Alembic commands ###
