version: "3"

services:

  web:
    build: .
    command: uvicorn main:app --host 0.0.0.0 --port 8000 --reload
    volumes:
      - ./homefinderbackend/:/main/
    ports:
      - "8000:8000"
    depends_on:
      - db
    environment:
      DATABASE_URL : postgresql://postgres:root@localhost:5432/homefinder_db

  db:
    image: postgres:16.1
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: root
      POSTGRES_DB: homefinder_db
      POSTGRES_PORT: 5432
      POSTGRES_HOST: localhost
    volumes:
          - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
